/*
 * CandyStore.java, KanjiCounting, Team Millennium
 * Play the candy store minigame
 */
package KanjiCounting;

import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author hdren
 */
public class CandyStore extends javax.swing.JFrame {

    int[] level;
    Number num;
    Random rnd;
    int mistakes = 0;
    int score = 0;
    
    int price;
    String priceK;
    int payment;
    String paymentK;
    String changeK;
    int answer;
    String answerK;
    String input;
    
    String intro = "You work as a cashier at a candy store and the cash register is broken so you have to do the work manually.\n"
            + "Make sure to give the correct change, or after so many times you'll be fired";
    String correct = "Nice job! You were right.";
    String incorrect = "Sorry, try again.";
    
    /**
     * Creates new form CandyStore
     */
    public CandyStore() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.yellow);
        jPanel1.setBackground(java.awt.Color.yellow);
        JOptionPane.showMessageDialog( null, intro);

        
        rnd = new Random();
        
        num = new Number(0);
        button0.setText(num.getNumberK());
        num.Number(1);
        button1.setText(num.getNumberK());
        num.Number(2);
        button2.setText(num.getNumberK());
        num.Number(3);
        button3.setText(num.getNumberK());
        num.Number(4);
        button4.setText(num.getNumberK());
        num.Number(5);
        button5.setText(num.getNumberK());
        num.Number(6);
        button6.setText(num.getNumberK());
        num.Number(7);
        button7.setText(num.getNumberK());
        num.Number(8);
        button8.setText(num.getNumberK());
        num.Number(9);
        button9.setText(num.getNumberK());
        num.Number(10);
        button10.setText(num.getNumberK());
        num.Number(100);
        button100.setText(num.getNumberK());
        
        this.setBackground(new java.awt.Color (255,255,0));
        
        setVisible(true);
        
    }
    
    public void CandyStore(int[] level) {
        this.level = level;
        
        nextOrder();
    }
    
    public void nextOrder() {
        price = 0;
        payment = 0;
        changeK = null;
        while (price < 1) {
            price = rnd.nextInt(level[level.length - 1]);
        }
        while (price > payment) {
            payment = rnd.nextInt(level[level.length - 1]);
        }
        
        num.setNumberK(price);
        priceK = num.getNumberK();
        num.setNumberK(payment);
        paymentK = num.getNumberK();
        answer = payment - price;
        num.setNumberK(answer);
        answerK = num.getNumberK();
        
        
        priceLabel.setText(priceK);
        paymentLabel.setText(paymentK);
        changeLabel.setText(changeK);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        priceLabel = new javax.swing.JLabel();
        cashRegisterLabel = new javax.swing.JLabel();
        paymentLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        button0 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button100 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        changeLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Candy Store");
        setBackground(new java.awt.Color(255, 255, 0));
        setLocation(new java.awt.Point(700, 200));
        setMaximumSize(new java.awt.Dimension(660, 365));
        setMinimumSize(new java.awt.Dimension(660, 365));
        setPreferredSize(new java.awt.Dimension(660, 365));
        setResizable(false);
        setSize(new java.awt.Dimension(660, 365));
        getContentPane().setLayout(null);

        priceLabel.setForeground(new java.awt.Color(0, 255, 0));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(priceLabel);
        priceLabel.setBounds(80, 20, 180, 30);

        cashRegisterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Game Pics/cash register.png"))); // NOI18N
        getContentPane().add(cashRegisterLabel);
        cashRegisterLabel.setBounds(0, 0, 350, 322);

        paymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        paymentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paymentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        paymentLabel.setOpaque(true);
        getContentPane().add(paymentLabel);
        paymentLabel.setBounds(410, 30, 170, 40);

        jLabel1.setText("They paid:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 0, 70, 30);

        jPanel1.setLayout(new java.awt.GridLayout(3, 4));

        button0.setToolTipText("rei");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        jPanel1.add(button0);

        button1.setToolTipText("ichi");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);

        button2.setToolTipText("ni");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);

        button3.setToolTipText("san");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3);

        button4.setToolTipText("shi");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4);

        button5.setToolTipText("go");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5);

        button6.setToolTipText("rok");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel1.add(button6);

        button7.setToolTipText("nana");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel1.add(button7);

        button8.setToolTipText("achi");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel1.add(button8);

        button9.setToolTipText("kyuu");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel1.add(button9);

        button10.setToolTipText("juu");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        jPanel1.add(button10);

        button100.setToolTipText("hyaku");
        button100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button100ActionPerformed(evt);
            }
        });
        jPanel1.add(button100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(390, 90, 210, 140);

        jLabel2.setText("Change:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 240, 50, 20);

        clearButton.setBackground(new java.awt.Color(255, 0, 51));
        clearButton.setText("X");
        clearButton.setToolTipText("Clear answer");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(590, 275, 40, 30);

        changeLabel.setEditable(false);
        changeLabel.setBackground(new java.awt.Color(255, 255, 255));
        changeLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        changeLabel.setToolTipText("Hit \"Enter\" to check your answer");
        changeLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changeLabel.setDragEnabled(true);
        changeLabel.setSelectionColor(new java.awt.Color(0, 0, 255));
        changeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLabelActionPerformed(evt);
            }
        });
        getContentPane().add(changeLabel);
        changeLabel.setBounds(410, 270, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button9.getText();
        else changeK += button9.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button9ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        changeK = null;
        changeLabel.setText(changeK);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button0.getText();
        else changeK += button0.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button0ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button1.getText();
        else changeK += button1.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button2.getText();
        else changeK += button2.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button3.getText();
        else changeK += button3.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button4.getText();
        else changeK += button4.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button5.getText();
        else changeK += button5.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button6.getText();
        else changeK += button6.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button7.getText();
        else changeK += button7.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button8.getText();
        else changeK += button8.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button8ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button10.getText();
        else changeK += button10.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button10ActionPerformed

    private void button100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button100ActionPerformed
        // TODO add your handling code here:
        if (changeK == null) changeK = button100.getText();
        else changeK += button100.getText();
        changeLabel.setText(changeK);
        changeLabel.requestFocus();
    }//GEN-LAST:event_button100ActionPerformed

    private void changeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLabelActionPerformed
        // TODO add your handling code here:
        input = changeLabel.getText();
        if (input.equals(answerK)) {
            JOptionPane.showMessageDialog( null, correct);
            score++;
            nextOrder();
        }
        else {
            JOptionPane.showMessageDialog( null, incorrect);
            mistakes++;
            if (mistakes == 10) {
                JOptionPane.showMessageDialog( null, "Oh no! You've been fired");
                JOptionPane.showMessageDialog( null, "Your score was: " + score);
                mistakes = 0;
                score = 0;
                nextOrder();
            }

        }
    }//GEN-LAST:event_changeLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandyStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button100;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JLabel cashRegisterLabel;
    private javax.swing.JTextField changeLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
