/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KanjiCounting;

import javax.swing.JOptionPane;

/**
 *
 * @author h-drennen
 */
public class MainMenu extends javax.swing.JFrame {
    
    // the following levels section off numbers 0-100 to better focus the student's learning
    int[] level1 = new int[11]; // level 1 are numbers 0-10
    int[] level2 = new int[11]; // level 2 are numbers 0-100 going by 10s
    int[] level3 = new int[101]; // level 3 are umbers 0-100
    int[] currentLevel; // this acts as a reference to the different levels
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        IntroDialog introDialog = new IntroDialog(this, true);
        introDialog.setVisible(true);
        // this loop will store level 1 as 0-10
        for (int i = 0; i <= 10; i++) {
            level1[i] = i;
        }
        // this loop will store level 2 as 0-100 going be 10s
        for (int i = 0; i <= 10; i++) {
            level2[i] = i * 10;
        }
        // this loop will store level 3 a 0-100
        for (int i = 0; i <= 100; i++) {
            level3[i] = i;
        }
        currentLevel = level1; // this is to initialize the current level as 1
    }
    
    /**
     * Get the current level selected.
     * @return int level chosen.
     */
    public int getLevel()
    {
        int level = Integer.parseInt(levelComboBox.getSelectedItem().toString());
        return level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        learnLabel = new javax.swing.JLabel();
        learnCountingButton = new javax.swing.JButton();
        learnFlashcardsButton = new javax.swing.JButton();
        miniGameLabel = new javax.swing.JLabel();
        gameTresHuntButton = new javax.swing.JButton();
        gameCandStoreButton = new javax.swing.JButton();
        levelLabel = new javax.swing.JLabel();
        levelComboBox = new javax.swing.JComboBox<>();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kanji Counting");
        setLocation(new java.awt.Point(700, 200));
        setMinimumSize(new java.awt.Dimension(444, 330));
        setSize(new java.awt.Dimension(444, 330));
        getContentPane().setLayout(null);

        learnLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        learnLabel.setText("Learn:");
        getContentPane().add(learnLabel);
        learnLabel.setBounds(150, 50, 77, 29);

        learnCountingButton.setText("Counting");
        learnCountingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnCountingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(learnCountingButton);
        learnCountingButton.setBounds(40, 110, 80, 23);

        learnFlashcardsButton.setText("Flashcards");
        learnFlashcardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnFlashcardsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(learnFlashcardsButton);
        learnFlashcardsButton.setBounds(260, 110, 110, 23);

        miniGameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        miniGameLabel.setText("Mini Games:");
        getContentPane().add(miniGameLabel);
        miniGameLabel.setBounds(134, 149, 131, 37);

        gameTresHuntButton.setText("Treasure Hunt");
        gameTresHuntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameTresHuntButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gameTresHuntButton);
        gameTresHuntButton.setBounds(30, 210, 120, 23);

        gameCandStoreButton.setText("Candy Store");
        gameCandStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameCandStoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gameCandStoreButton);
        gameCandStoreButton.setBounds(250, 210, 110, 23);

        levelLabel.setText("Level:");
        getContentPane().add(levelLabel);
        levelLabel.setBounds(279, 10, 40, 14);

        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        levelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(levelComboBox);
        levelComboBox.setBounds(330, 10, 40, 20);

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton);
        helpButton.setBounds(40, 10, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelComboBoxActionPerformed
        // TODO add your handling code here:
        // the switch block will change the reference of currentlevel to the level the choose
        switch (Integer.parseInt((String) levelComboBox.getSelectedItem())) {
            case 1: currentLevel = level1; break;
            case 2: currentLevel = level2; break;
            case 3: currentLevel = level3; break;
        }
    }//GEN-LAST:event_levelComboBoxActionPerformed

    private void gameTresHuntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameTresHuntButtonActionPerformed
        // open treasure hunt game
        TreasureHunt treasHunt = new TreasureHunt();
        treasHunt.TreasureHunt(currentLevel);
    }//GEN-LAST:event_gameTresHuntButtonActionPerformed

    private void learnCountingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnCountingButtonActionPerformed
        // open counting game
        CountingGame countingGame = new CountingGame();
        countingGame.CountingGame(currentLevel);
    }//GEN-LAST:event_learnCountingButtonActionPerformed

    private void learnFlashcardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnFlashcardsButtonActionPerformed
       // open flashcards
        new Flashcards().setVisible(true);
    }//GEN-LAST:event_learnFlashcardsButtonActionPerformed

    private void gameCandStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameCandStoreButtonActionPerformed
        // TODO add your handling code here:
        CandyStore candyStore = new CandyStore();
        candyStore.CandyStore(currentLevel);
    }//GEN-LAST:event_gameCandStoreButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog( null, "Learn how to count with the Kanji symbols in the \"Learn\" section." +
                "\nHone your skills by playing some games in the \"Mini Game\" section."
                + "\nYou can change the range of numbers that you are learning by changing the level."
        + "\n\n Level 1 is 0-10 \n Level 2 is 0-100 in 10s \n Level 3 is all numbers 0-100");
    }//GEN-LAST:event_helpButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameCandStoreButton;
    private javax.swing.JButton gameTresHuntButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton learnCountingButton;
    private javax.swing.JButton learnFlashcardsButton;
    private javax.swing.JLabel learnLabel;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel miniGameLabel;
    // End of variables declaration//GEN-END:variables
}
